import Head from "next/head";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import "@/styles/globals.css";
import { UserProvider } from "@/utils/UserContext";
import { Provider } from "react-redux";
import { PersistGate } from "redux-persist/integration/react";
import { store, persistor } from "../store/store";
function App({ Component, pageProps, router }) {
  const isAdmin = router.pathname.startsWith(
    "/admin" || "/products" || "settings" || "orders"
  );

  const isShipper = router.pathname.startsWith("/shipper");
  if (isAdmin) {
    // Trang admin
    return <Component {...pageProps} />;
  }
  if (isShipper) {
    // Trang shipper
    return <Component {...pageProps} />;
  }
  return (
    <>
      <Head>
        <title>Online Shoe Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;500;600;700&family=Urbanist:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Provider store={store}>
        <PersistGate loading={null} persistor={persistor}>
          <UserProvider>
            <Header />
            <Component {...pageProps} />
            <Footer />
          </UserProvider>
        </PersistGate>
      </Provider>
    </>
  );
}
export default App;
